server:
  port: 8001

spring:
  application:
    name: property
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/property?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: root
    password: root


swagger:
  enable: true

mybatis-plus:
  configuration:
    #map-underscore-to-camel-case: false #mybatis-plus\u5173\u95ED\u4E0B\u5212\u7EBF\u9A7C\u5CF0\u547D\u540D\uFF0C\u8BC6\u522B\u6570\u636E\u5E93\u7D22\u5F15 "_"
    #log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl #\u65E5\u5FD7
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:/mapper/*.xml